#!/usr/bin/env python3
"""
Generates assets/hero.svg — a hand-authored animated banner (starfield,
comet streaks, a rotating gradient ring, and a shimmer-sweep on the title
text) styled to match the Vault design system (dark background, indigo
#818cf8 -> purple #c084fc gradients). No third-party badge/banner service
involved — every animated element below is native SVG SMIL, generated by
this script and committed as a static asset.

Re-run with `python3 scripts/generate_hero.py` any time the design should
change; the star/comet layout is seeded for reproducibility.
"""
import random

random.seed(13)

WIDTH, HEIGHT = 1200, 280
INDIGO = "#818cf8"
PURPLE = "#c084fc"

def stars(n=80):
    out = []
    for _ in range(n):
        cx = round(random.uniform(20, WIDTH - 20), 1)
        cy = round(random.uniform(15, HEIGHT - 15), 1)
        r = round(random.uniform(0.4, 1.7), 2)
        dur = round(random.uniform(2.2, 5.5), 2)
        begin = round(random.uniform(0, 5), 2)
        base_op = round(random.uniform(0.15, 0.35), 2)
        peak_op = round(random.uniform(0.6, 0.95), 2)
        out.append(
            f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="#ffffff">'
            f'<animate attributeName="opacity" values="{base_op};{peak_op};{base_op}" '
            f'dur="{dur}s" begin="{begin}s" repeatCount="indefinite" /></circle>'
        )
    return "\n    ".join(out)

def comets(n=3):
    out = []
    paths = [
        "M -60,230 L 1260,40",
        "M -60,60 L 1260,220",
        "M -60,150 L 1260,110",
    ]
    for i in range(n):
        dur = round(random.uniform(6, 9), 2)
        begin = round(i * 3.4 + random.uniform(0, 2), 2)
        out.append(f"""
    <g opacity="0">
      <line x1="0" y1="0" x2="46" y2="0" stroke="url(#cometGrad)" stroke-width="1.6" stroke-linecap="round" />
      <animateMotion path="{paths[i % len(paths)]}" dur="{dur}s" begin="{begin}s" repeatCount="indefinite" rotate="auto" />
      <animate attributeName="opacity" values="0;0;0.85;0.85;0" keyTimes="0;0.02;0.12;0.85;1"
               dur="{dur}s" begin="{begin}s" repeatCount="indefinite" />
    </g>""")
    return "".join(out)

svg = f"""<svg width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bgGrad" x1="0" y1="0" x2="{WIDTH}" y2="{HEIGHT}" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#0a0a14" />
      <stop offset="1" stop-color="#050508" />
    </linearGradient>
    <linearGradient id="textGrad" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="{INDIGO}" />
      <stop offset="1" stop-color="{PURPLE}" />
    </linearGradient>
    <linearGradient id="shimmerGrad" x1="-200" y1="0" x2="0" y2="0" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#ffffff" stop-opacity="0" />
      <stop offset="0.45" stop-color="#ffffff" stop-opacity="0" />
      <stop offset="0.5" stop-color="#ffffff" stop-opacity="0.75" />
      <stop offset="0.55" stop-color="#ffffff" stop-opacity="0" />
      <stop offset="1" stop-color="#ffffff" stop-opacity="0" />
      <animate attributeName="x1" values="-400;1400" dur="4.5s" begin="0.5s" repeatCount="indefinite" />
      <animate attributeName="x2" values="-200;1600" dur="4.5s" begin="0.5s" repeatCount="indefinite" />
    </linearGradient>
    <linearGradient id="ringGrad" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{INDIGO}" stop-opacity="0" />
      <stop offset="0.5" stop-color="{INDIGO}" />
      <stop offset="1" stop-color="{PURPLE}" stop-opacity="0" />
    </linearGradient>
    <linearGradient id="cometGrad" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="{PURPLE}" stop-opacity="0" />
      <stop offset="1" stop-color="#ffffff" stop-opacity="0.9" />
    </linearGradient>
    <clipPath id="roundedClip">
      <rect x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="18" ry="18" />
    </clipPath>
  </defs>

  <g clip-path="url(#roundedClip)">
    <rect x="0" y="0" width="{WIDTH}" height="{HEIGHT}" fill="url(#bgGrad)" />

    <!-- starfield -->
    {stars()}

    <!-- comet streaks -->
    {comets()}

    <!-- rotating gradient ring around the monogram -->
    <g>
      <circle cx="120" cy="140" r="54" fill="none" stroke="url(#ringGrad)" stroke-width="3"
              stroke-dasharray="115 225" stroke-linecap="round">
        <animateTransform attributeName="transform" type="rotate" from="0 120 140" to="360 120 140"
                           dur="7s" repeatCount="indefinite" />
      </circle>
      <circle cx="120" cy="140" r="44" fill="#12121c" stroke="rgba(255,255,255,0.08)" stroke-width="1" />
      <text x="120" y="156" font-family="'Segoe UI', Ubuntu, sans-serif" font-size="40" font-weight="700"
            text-anchor="middle" fill="#ffffff">R</text>
    </g>

    <!-- title -->
    <text x="205" y="128" font-family="'Segoe UI', Ubuntu, sans-serif" font-size="54" font-weight="700"
          letter-spacing="0.5" fill="url(#textGrad)">Rahul Khanna</text>
    <text x="205" y="128" font-family="'Segoe UI', Ubuntu, sans-serif" font-size="54" font-weight="700"
          letter-spacing="0.5" fill="url(#shimmerGrad)">Rahul Khanna</text>

    <!-- subtitle -->
    <text x="207" y="162" font-family="'Segoe UI', Ubuntu, sans-serif" font-size="19" fill="rgba(255,255,255,0.5)">
      Software Engineer &#183; Builder &#183; Competitive Programmer
    </text>

    <!-- terminal tagline -->
    <text x="207" y="210" font-family="'Fira Code', 'Courier New', monospace" font-size="15" fill="{INDIGO}">
      &gt; designing systems for an audience of one<tspan fill="#ffffff">
        <animate attributeName="opacity" values="1;1;0;0" keyTimes="0;0.5;0.51;1" dur="1s" repeatCount="indefinite" />_</tspan>
    </text>
  </g>

  <rect x="0.5" y="0.5" width="{WIDTH - 1}" height="{HEIGHT - 1}" rx="18" ry="18"
        fill="none" stroke="rgba(129,140,248,0.25)" stroke-width="1" />
</svg>
"""

if __name__ == "__main__":
    with open("assets/hero.svg", "w") as f:
        f.write(svg)
    print(f"wrote assets/hero.svg ({len(svg)} bytes)")
